# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Lounges
    url: lounges/
    weight: 20
    hasChildren: true
  - parent: Lounges
    name: Buda
    url: lounges/buda/
  - parent: Lounges
    name: East Austin
    url: lounges/eastaustin/
  - parent: Lounges
    name: San Marcos
    url: lounges/sanmarcos/
  - parent: Lounges
    name: Bee Cave
    url: lounges/beecave/
  - name: Events
    url: events/
    weight: 30
  - name: Featured Cigar Brands
    weight: 40
    hasChildren: true
  - parent: Featured Cigar Brands
    name: Aladino
    url: https://www.jretobacco.com/portfolio/aladino/
  - parent: Featured Cigar Brands
    name: Definition
    url: https://definitioncigars.com/our-cigars/
  - parent: Featured Cigar Brands
    name: RoMa Craft
    url: https://romacrafttobac.com/
  - name: Private Events 
    url: privateevents/
    weight: 50

