# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Lounges
    url: /#lounges
    weight: 20
    hasChildren: true
  - parent: Lounges
    name: Buda
    url: buda/
  - parent: Lounges
    name: East Austin
    url: eastaustin/
  - parent: Lounges
    name: San Marcos
    url: sanmarcos/
  - parent: Lounges
    name: Bee Cave
    url: beecave/
  - name: Events
    url: /#events
    weight: 30
  - name: Announcements
    url: /#announcements
    weight: 40
  - name: Featured Brands
    weight: 50
    hasChildren: true
  - parent: Featured Brands
    name: Aladino
    url: aladino/
  - parent: Featured Brands
    name: Definition
    url: definition/
  - parent: Featured Brands
    name: RoMa Craft
    url: romacraft/
